version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '%(levelname)s - %(message)s'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "module": "%(module)s", "function": "%(funcName)s", "message": "%(message)s"}'
    datefmt: '%Y-%m-%dT%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  
  profile_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: profiles.log
    maxBytes: 10485760
    backupCount: 5
  
  database_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: database.log
    maxBytes: 10485760
    backupCount: 5
  
  task_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: tasks.log
    maxBytes: 10485760
    backupCount: 5
  
  automation_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: automation.log
    maxBytes: 10485760
    backupCount: 5
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: errors.log
    maxBytes: 10485760
    backupCount: 10

loggers:
  profile_automation:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: false
  
  profile_automation.profiles:
    level: DEBUG
    handlers: [profile_file, error_file]
    propagate: false
  
  profile_automation.database:
    level: DEBUG
    handlers: [database_file, error_file]
    propagate: false
  
  profile_automation.tasks:
    level: DEBUG
    handlers: [task_file, error_file]
    propagate: false
  
  profile_automation.automation:
    level: DEBUG
    handlers: [automation_file, error_file]
    propagate: false
  
  selenium:
    level: WARNING
    handlers: [file_handler]
    propagate: false
  
  urllib3:
    level: WARNING
    handlers: [file_handler]
    propagate: false

root:
  level: INFO
  handlers: [console, file_handler, error_file]
